# Generated by Django 4.2.4 on 2023-08-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular_blogs',
            name='image',
            field=models.ImageField(upload_to='popular_Blog/'),
        ),
    ]
