# Generated by Django 4.2.4 on 2023-08-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_alter_popular_blogs_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='regular_blog',
            name='url',
        ),
    ]
