# Generated by Django 4.2.3 on 2023-08-07 12:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_popular_blogs_regular_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular_blogs',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='regular_blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
