# Generated by Django 4.2.3 on 2023-08-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_alter_popular_blogs_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Popular_Blogs',
        ),
        migrations.DeleteModel(
            name='Regular_Blog',
        ),
    ]
