# Generated by Django 4.2.3 on 2023-08-08 19:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_delete_popular_blogs_remove_regular_blog_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=90)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Popular_Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=90)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regular_Blog',
            fields=[
                ('Blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=90)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Regular_Blog/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.category')),
            ],
        ),
    ]
