# Generated by Django 4.2.3 on 2023-08-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0009_category_regular_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regular_blog',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Regular_Blog',
        ),
    ]
